"use client";

import "./globals.css";
// fonts
import { Sora } from "next/font/google";

// font settings
const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

// components
import Nav from "../components/Nav";
import Header from '../components/Header';
import Transition from "../components/Transition";
import TopLeftImg from '../components/TopLeftImg';

// framer motion
import { AnimatePresence, motion } from "framer-motion";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AnimatePresence mode="wait">
          <motion.div className="h-full">
            <Transition />
            <main
              className={`page bg-site text-white bg-cover bg-no-repeat ${sora.variable} font-sora relative`}
            >
              <TopLeftImg/>
              <Nav />
              <Header/>
              {children}
            </main>
          </motion.div>
        </AnimatePresence>
      </body>
    </html>
  );
}
